### ISSUE TITLE
Run lexer panics if last line is non-empty

### ISSUE THREAD

**Issue by chabad360** [TekWizely/run#1]
If the last line of my `Runfile` isn't empty, run throws the following error:

```
panic: Lexer.Next: No rune available

goroutine 1 [running]:
github.com/tekwizely/go-parsing/lexer.(*Lexer).Next(0xc0000cc1e0, 0x521c00)
        /workspace/go/pkg/mod/github.com/tekwizely/go-parsing/lexer@v0.0.0-20190714215300-5be83bb42370/lexer.go:159 +0x102
github.com/tekwizely/run/internal/lexer.lexCmdScriptLine(0xc0000bc020, 0xc0000cc1e0, 0x4f31e0)
        /workspace/run/internal/lexer/lexer.go:690 +0xe4
github.com/tekwizely/run/internal/lexer.(*LexContext).lex(0xc0000bc020, 0xc0000cc1e0, 0x4e91c0)
        /workspace/run/internal/lexer/lexer.go:41 +0x7e
github.com/tekwizely/go-parsing/lexer.(*tokenNexter).hasNext(0xc0000bc040, 0x7f6291d24460)
        /workspace/go/pkg/mod/github.com/tekwizely/go-parsing/lexer@v0.0.0-20190714215300-5be83bb42370/tokennexter.go:55 +0x9d
github.com/tekwizely/go-parsing/lexer.(*tokenNexter).Next(0xc0000bc040, 0x0, 0x0, 0xc0000a43d0, 0xc0000aca20)
        /workspace/go/pkg/mod/github.com/tekwizely/go-parsing/lexer@v0.0.0-20190714215300-5be83bb42370/tokennexter.go:22 +0x2f
github.com/tekwizely/go-parsing/parser.(*Parser).growPeek(0xc0000d0050, 0x1, 0x0)
        /workspace/go/pkg/mod/github.com/tekwizely/go-parsing/parser@v0.0.0-20190714215300-5be83bb42370/parser.go:199 +0x75
github.com/tekwizely/go-parsing/parser.(*Parser).CanPeek(...)
        /workspace/go/pkg/mod/github.com/tekwizely/go-parsing/parser@v0.0.0-20190714215300-5be83bb42370/parser.go:59
github.com/tekwizely/run/internal/parser.expectCmdScript(0xc0000bc080, 0xc0000d0050, 0xc0000a6540, 0x5, 0x0)
        /workspace/run/internal/parser/parser.go:630 +0x41c
github.com/tekwizely/run/internal/parser.tryMatchCmd(0xc0000bc080, 0xc0000d0050, 0xc0000d6000, 0xc0000c6000)
        /workspace/run/internal/parser/parser.go:238 +0x149
github.com/tekwizely/run/internal/parser.parseMain(0xc0000bc080, 0xc0000d0050, 0x4f3240)
        /workspace/run/internal/parser/parser.go:200 +0xa45
github.com/tekwizely/run/internal/parser.(*parseContext).parse(0xc0000bc080, 0xc0000d0050, 0x4ff720)
        /workspace/run/internal/parser/parser.go:46 +0x7f
github.com/tekwizely/go-parsing/parser.(*astNexter).hasNext(0xc0000bc0a0, 0xc0000d0050)
        /workspace/go/pkg/mod/github.com/tekwizely/go-parsing/parser@v0.0.0-20190714215300-5be83bb42370/astnexter.go:58 +0x97
github.com/tekwizely/go-parsing/parser.(*astNexter).Next(0xc0000bc0a0, 0xc0000bc040, 0xc0000a4370, 0x53c700, 0xc0000bc0a0)
        /workspace/go/pkg/mod/github.com/tekwizely/go-parsing/parser@v0.0.0-20190714215300-5be83bb42370/astnexter.go:30 +0x2f
github.com/tekwizely/run/internal/parser.Parse(0xc0000bc020, 0x1e)
        /workspace/run/internal/parser/parser.go:79 +0x133
main.main()
        /workspace/run/main.go:125 +0x507
```

**Comment by TekWizely** [comment]
Hey @chabad360,

This seems like a bug I might have introduced recently, however I am unable to duplicate it locally.

Can you provide a sample runfile that produces the error?

Q: What system are you on?  I'm on a MAC
Q: Can you confirm what file encoding you're using?
Q: Can you confirm what type of line-endings your using?

I'll be happy to try to fix this once I can reproduce it.

Thank you for taking the time to submit an issue.

Also: Thanks for all your support on HN - Much appreciated !

**Comment by chabad360** [comment]
> **Can you provide a sample Runfile that produces the error?**

```
hello:
	echo "hi"
```

> **Q: What system are you on?**

`uname -sor`: `Linux 4.14.145+ GNU/Linux`

> **Q: Can you confirm what file encoding you're using?**

UTF-8

> **Q: Can you confirm what type of line-endings you're using?**

LF (i.e. `\n`)

It appears this issue shows up when the file lacks a line ending.

> Also: Thanks for all your support on HN - Much appreciated!

You're welcome!

**Comment by TekWizely** [comment]
@chabad360 , thanks for the details - I think my editor was adding a trailing newline which is why I couldn't duplicate it.

The fix is in - Please let me know you're still having issues in that regard.

Thanks !

-TW

**Comment by chabad360** [comment]
nope, I've since tested it and it works like a charm!

by the way, I love your codebase (it's so well documented), how long
did this project take?

On 12/18/19, TekWize.ly <notifications@github.com> wrote:
> @chabad360 , thanks for the details - I think my editor was adding a
> trailing newline which is why I couldn't duplicate it.
>
> The fix is in - Please let me know you're still having issues in that
> regard.
>
> Thanks !
>
> -TW
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/TekWizely/run/issues/1#issuecomment-567303096


-- 
Mendel G
chabad360@gmail.com

**Comment by TekWizely** [comment]
> nope, I've since tested it and it works like a charm!

Woot !

> by the way, I love your codebase (it's so well documented), how long did this project take?

Thanks ! So I just looked into my notes and here are the details:
* 2018/10/26 : First notes on the idea
* 2019/07/03 : Local repo created
* 2019/07/05 : First code commit : 
`First working prototype, executes named scripts in bash`

**Comment by TekWizely** [comment]
@all-contributors please add @chabad360  for bug
