### ISSUE TITLE
How can I pass options to nodejs ?

### ISSUE THREAD

**Issue by dinh** [TekWizely/run#13]
This is what I do but it doesn't work :

```
# OPTION SCRIPT -s,--script <script> JS codeintegration  
hellonode (node):
  console.log(${SCRIPT})
  eval(${SCRIPT})
```

**Comment by TekWizely** [comment]
Hi @dinh ,

Thank you for taking the time to post your question.

The first thing I notice is that you have `${SCRIPT}` 

I don't think this is the correct way to access environment variables from node?

I think you need something like `process.env.SCRIPT`

See: https://stackoverflow.com/questions/4870328/read-environment-variables-in-node-js

Hope that helps,

-TW

PS: For future discussion, try to post the following when reporting an issue:
- How you are invoking the commend
- What error messages you are seeing

**Comment by TekWizely** [comment]
Hi @dinh ,

I also just realized that your header is wrong, it should be:
```
##
# OPTION SCRIPT -s,--script <script> JS codeintegration  
hellonode (node):
  console.log(${SCRIPT})
  eval(${SCRIPT})
```

The leading `##` is very important

**Comment by TekWizely** [comment]
Hi @dinh please post and let me know if you got it working?

Thanks!

-TW

**Comment by dinh** [comment]
Hi @TekWizely , `process.env.SCRIPT` is indeed the right way to get the `SCRIPT` environment variable in nodejs.

If `SCRIPT` is passed in a bash script, don't forget to enclose the variable in double quotes like such : 

`run myNodeScript "${SCRIPT}" `
