### ISSUE TITLE
Searchability

### ISSUE THREAD

**Issue by lil5** [TekWizely/run#43]
I cant find the project using the github search and need to scroll down through my github stars.

Might i suggest adding the following search tags to improve searchability;

```
run
runfile
makefile
make
```

**Comment by TekWizely** [comment]
Done and thanks for the heads up !  

Thanks for taking the time - I would love to learn more about how you're using Run.

I noticed your `maakfile` project which looks cool.

Good luck with it and thanks again !

**Comment by lil5** [comment]
@TekWizely 

Yes I started with maakfile project because I hadn't found a script runner other than npm script + `npm-run-all` that fit my needs (run stuff as if I were in a bash terminal, async exec, watch files), TOML's syntax verbosity was what pushed me to use `run` instead, I might use your parser in the future for Maakfile :shrug: 

`reflex` plus `run` if able to do most of what I need, here's my Runfile.

```makefile
start-go:
	go run main.go
start-css:
	npx tailwindcss -c ./local/views/postcss/tailwind.config.js -i ./local/views/postcss/tailwind.postcss -o ./local/views/assets/css/tailwind.min.css

dev-go:
	~/go/bin/reflex -s -r '\.(go|gohtml)$' run start-go
dev-css:
	~/go/bin/reflex -s -r 'tailwind\.(postcss|config\.js)$' run start-css

build:
	run build-css
	run build-go

build-css:
	NODE_ENV=production npx tailwindcss --purge local/views/html/*.gohtml --minify -c ./local/views/postcss/tailwind.config.js -i ./local/views/postcss/tailwind.postcss -o ./local/views/assets/css/tailwind.min.css
build-go:
	go build -o binary main.go

test:
	go test ./...
test-watch:
	~/go/bin/reflex -s -r '\.(go)$' run test

dependencies:
	npm install
	go get
	cp node_modules/alpinejs/dist/cdn.min.js local/views/assets/js/alpinejs.min.js
	go install github.com/cespare/reflex@latest
```

**Comment by TekWizely** [comment]
Thanks for sharing !

Re:
>  having an parallel feature would be great ...

So this _feels_ like something your shell could likely take care of.

I did some googling :
* [bash start two background processes wait for them to finish](https://www.google.com/search?q=bash+start+two+background+processes+wait+for+them+to+finish)

And came across this discussion:
* [How to wait in bash for several subprocesses to finish and return exit code !=0 when any subprocess ends with code !=0?](https://stackoverflow.com/questions/356100/how-to-wait-in-bash-for-several-subprocesses-to-finish-and-return-exit-code-0)

From which I derived this test Runfile for you to try:

_Runfile_
```
.SHELL=bash

test-ok:
	cmds=( "run test1" "run test2" )
	run wait "${cmds[@]}"

test-err:
	cmds=( "run test1" "run test2" "run test3" )
	run wait "${cmds[@]}"

test1:
	echo "test1"
	exit 0

test2:
	echo "test2"
	exit 0

test3:
	echo "test3"
	exit 1

wait:
	pids=""
	for cmd in "$@"; do
		${cmd} &
		pids="$pids $!"
	done

	exit_code=0
	for pid in $pids; do
		pid_result=0
		wait $pid || pid_result=$?
		if [ ! "$pid_result" == "0" ]; then
			printf "pid %s exited with code %d\n" "$pid" "$pid_result"
			exit_code=$pid_result
		fi
	done

	exit $exit_code
```

_usage_
```
$ run test-ok
test2
test1

$ run test-errr
test1
test2
test3
pid 99652 exited with code 1
```

This is just a prototype but I think it could work as the basis for a useful run command.

Give it a try and lemme know how it goes !

**Comment by TekWizely** [comment]
Re-opening since we have an active conversation :)

**Comment by lil5** [comment]
Haha no need, If I'm going to need to add that below I might as well use something like https://github.com/octolab/parallel

```sh
wait:
	pids=""
	for cmd in "$@"; do
		${cmd} &
		pids="$pids $!"
	done

	exit_code=0
	for pid in $pids; do
		pid_result=0
		wait $pid || pid_result=$?
		if [ ! "$pid_result" == "0" ]; then
			printf "pid %s exited with code %d\n" "$pid" "$pid_result"
			exit_code=$pid_result
		fi
	done

	exit $exit_code
```

I chose to use this project instead of GNU Make because it is simple and doesn't require escaping characters like `$`.

**Comment by TekWizely** [comment]
Parallel is great but I was trying to get something that could be self-contained within the Runfile.

I am grinding on a way to allow commands to  pre-run other commands, but need to nail down the syntax, ie. specify sequential / parallelism, specify how to treat failures, etc ... 

Lemme know if you have some ideas on what that syntax might look like?

Thanks again for participating in my project !
