### ISSUE TITLE
Support includes

### ISSUE THREAD

**Issue by nikolay** [TekWizely/run#44]
It would be nice to be able to include other runfiles, including using wildcards with `*` and `**`. This way, you can have top-level commands at the root of the project, and it can include commands for modules that are nested deeply. For example:

```Runfile
IMPORT **/Runfile
```

or:

```Runefile
IMPORT "component1/Runfile"
...
IMPORT "componentN/Runfile"
```

**Comment by nikolay** [comment]
@TekWizely I can try to contribute this, but I'm still a Go novice. Is this possible to be done or should I work on some hack to accomplish the same?

**Comment by TekWizely** [comment]
Hi @nikolay ! Sorry for the late response ...

I have started working on this and will have a PR up soon - I'll ping you on it so you can have a look.

NOTE: I'm looking into [goreleaser/fileglob](https://github.com/goreleaser/fileglob) for possible globbing support, but I'm not sure its ready for prime time and so may not have \*/\*\* support in the initial version.

Stay Tuned !

---

cc @charandas

**Comment by nikolay** [comment]
🙇🏻 Thank you, @TekWizely! This is really great news!

**Comment by nikolay** [comment]
@TekWizely Thanks for implementing this great feature! Is it going to be released soon?

**Comment by TekWizely** [comment]
Hi @nikolay,

Still a few features standing in front of the next release: #47 ( with PR #51 ), #52 (PR pending)

These are basically out-crops of the INCLUDE support that I feel need to be resolved so the next release will feel more complete.

Feel free to chime in on those with your thoughts,

-TW

**Comment by TekWizely** [comment]
> @TekWizely Thanks for implementing this great feature! Is it going to be released soon?

Quick update:

I've decided that #60 is worth waiting for, as it could make working with the newly added `.RUNFILE.DIR` and `.SELF.DIR` attributes a bit easier, but no other outstanding issues are planned to hold up the next release, so keep an eye out for a release soon after #60 gets merged !

(also feel free take a review pass at the new feature and leave your feedback)

**Comment by TekWizely** [comment]
Greetings @nikolay !

Just a quick note to let you know that [v0.9.0](https://github.com/TekWizely/run/releases/tag/v0.9.0) has been released !  A [PR](https://github.com/Homebrew/homebrew-core/pull/109591) has been created to update the official Homebrew formula, but in the meantime my personal [tap](https://github.com/TekWizely/homebrew-tap) has already been updated, as well as the [npm](https://www.npmjs.com/package/@tekwizely/run) install.

Thank you for your patience!

-TW

**Comment by nikolay** [comment]
Thank you very much, @TekWizely! Great work!
