### ISSUE TITLE
Homebrew formula?

### ISSUE THREAD

**Issue by geoelectric** [TekWizely/run#6]
I see the note on the README re: the package manager support upcoming. 

Is this something you need help with? I've never created a homebrew formula, but since my first thought on reading the HN article was whether I could `brew install` it, I guess it might be important.

If you're not already working on that in an outstanding branch, it sounds straightforward enough that I could maybe give it a shot and give you a PR for one hosted in your own repo as a tap.

**Comment by TekWizely** [comment]
Greetings @geoelectric !

I am not currently working on it and could definitely use the help!

Please feel free to fork the project and create a `"brew"` branch (or somesuch) - I'd love to see the PR and learn about the process - I use brew as well and feel a little bad that I don't already know how to create brew formula from go packages.

Thank you for the offer and please let me know if you have any other questions need any help!

**Comment by dawidd6** [comment]
Homebrew maintainer here.

I can make a formula for this project and make a PR to `homebrew-core`, but first you would need to make a release, because Homebrew does not allow unversioned projects generally.

**Comment by geoelectric** [comment]
I'm sure having something directly in homebrew-core would be advantageous over the private tap, so I'll wait for some guidance on how @TekWizely wants to proceed with that.

In the meantime, I'll start looking into how to spin a formula for a go project, because I still want to know how to do it for myself!

**Comment by dawidd6** [comment]
Just have a look at man page of `brew create`.

**Comment by TekWizely** [comment]
Greetings @dawidd6 !

I appreciate your willingness to help!

I have two issues I want to resolve (#3 and #7) and then I think we'll be in a good place to cut a release.

OTOH, maybe I should just make one with the current code to keep things moving.

Q: Can I just use the standard github Release mechanism or do I need specific assets in the release?

Lemme know and thanks again - I'm very excited about this !

-TW

**Comment by dawidd6** [comment]
Just a plain git tag or github release are fine.

**Comment by TekWizely** [comment]
OK Release `v.0.5.1` has been cut !
* https://github.com/TekWizely/run/releases/tag/v0.5.1

Please let me know if I can do anything else to help, thanks!

**Comment by dawidd6** [comment]
PR is up: https://github.com/Homebrew/homebrew-core/pull/48100

**Comment by geoelectric** [comment]
This was pretty impressive collaboration. I’m glad I at least created a thread!

@TekWizely — looks like you’re covered here, but I’ll try to find other ways to contribute. I really like what you’re building.

**Comment by TekWizely** [comment]
@dawidd6 Woot! I have subscribed to the PR thread

Q: Do you need anything else from me in regards to the PR?  I.e comments, code changes, etc?

@geoelectric Thanks a lot for getting this thread started !  We both learned more about packaging projects for brew :)

Please let me know how Run holds up as you put it through some real-world scenarios.  I'm planning to start a Runfile repository as patterns and use-cases emerge, so I'd love to see what you come up with.

**Comment by dawidd6** [comment]
> Q: Do you need anything else from me in regards to the PR? I.e comments, code changes, etc?

@TekWizely not at this moment, thanks.

**Comment by TekWizely** [comment]
@dawidd6 I did a warning on that in your original PR:

> Warning: Generic binaries were installed to "/home/linuxbrew/.linuxbrew/opt/run/bin"
> Binaries with generic names are likely to conflict with other software,
> and suggest that this software should be installed to "libexec" and then
> symlinked as needed.
> 

Can you explain the `libexec` suggestion?  Is that something to consider?

`run` doesn't *appear* to be an existing linux command from my research, and I do very much like the name, so 🤞 we can use it.

**Comment by dawidd6** [comment]
It's been already adjusted in `brew` itself. Just need to wait for a maintainer to approve the PR and `run` will be available to install!

**Comment by TekWizely** [comment]
OK Run is now officially on Brew Core !

I have also updated the README with instructions.

Thank you @dawidd6  and @geoelectric for the help !

**Comment by TekWizely** [comment]
@all-contributors please add @dawidd6  for infra
