### ISSUE TITLE
Required options and default option values

### ISSUE THREAD

**Issue by nikolay** [TekWizely/run#61]
FIrst, the documentation section is called "arguments", but the keyword used is "option", which is a bit inconsistent. Second, it's too much extra work just to enforce required (usually non-boolean) options. It would be nice to have `OPTION?` as an alternative to `OPTION` and `OPTION!` for the required ones. Parsing a default value from the docstring would also make the usa DRY and ease up development.

**Comment by TekWizely** [comment]
Hey @nikolay  nice to hear from you ! Okay let's take a look ...

>  the documentation section is called "arguments", but the keyword used is "option"

I'm assuming you are referring to the [Arguments](https://github.com/TekWizely/run#arguments) section of the README...

That section is actually very small and just contains the `echo "Hello, ${1}"` example.

The very next section is titled [Command-Line Options](https://github.com/TekWizely/run#command-line-options), which goes into the `OPTION` configuration.

As you probably know, OPTIONS and ARGUMENTS are closely related but not exactly the same, and trying to discuss both of them at the same time can seem confusing, but I believe that the README does a decent job of distinguishing between the two.

Please feel free to point out some exact references that you're concerned about, and I'll be happy to take a further look.

> It would be nice to have OPTION? as an alternative to OPTION and OPTION!

> Parsing a default value from the docstring would also make the usa DRY and ease up development.


I have to agree that being able to mark a value as required and auto-generate error messages when missing will be a nice feature.

Additionally, providing a default value in the docstring seems very useful as well.

However, I'm not sure I like the indicators being on the OPTION keyword --  What would you think of these:

_Implicit Optional (Current Behavior)_
```
# OPTION NAME  -n,--name <name> Name to say hello to
```

_Explicit Optional_
```
# OPTION NAME? -n,--name <name> Name to say hello to
```

_Explicit Required_
```
# OPTION NAME! -n,--name <name> Name to say hello to
```

_Optional With Default Value_
```
# OPTION NAME=newman -n,--name <name> Name to say hello to
```

I'm not entirely sure that "Explicit Optional" is needed, so I may just try coding Required and Default to start ... 

What do you think?

**Comment by nikolay** [comment]
@TekWizely Your idea is even better! It makes a lot more sense especially with the intuitive syntax to provide a default value!

**Comment by TekWizely** [comment]
@nikolay I just opened a PR for this.

NOTE: I decided to with `?=` for the default assignment, to better-align with the Optional Variable assignment technique.
