### ISSUE TITLE
RUNFILE_ROOTS and RUNFILE

### ISSUE THREAD

**Issue by xkcd386at** [TekWizely/run#67]
Hello

I like the Runfile to be called ".runfile"; this is achieved by using RUNFILE env var.

I also like the runfile to be searched up in the path till one is found.  This is achieved by using RUNFILE_ROOTS.

Unfortunately it is not possible to ~~do~~combine both these ~~things~~features.

Could you make RUNFILE_ROOTS search for $RUNFILE if it is supplied, instead of "Runfile" ?

Thank you!

**Comment by TekWizely** [comment]
Hi and thanks for opening an issue.

The initial thoughts for $RUNFILE were that it would be an _absolute_ path to point to a runfile when you weren't in the folder containing the file.

BUT your idea of using it as a relative value to change the default runfile is pretty clever !

I think there's a possibility to achieve your request, something like:

* if $RUNFILE is defined and contains a _relative_ path, treat it as the search target in the RUNFILE_ROOTS logic.

I'll grind on it some more but I think this will work - keep an eye out for new pull request soon.

Thanks again for participating in my project.  Additionally, I'd love to know more about how you're using Run if you have a chance to share?

**Comment by TekWizely** [comment]
Hi @xkcd386at Please see #69 and give it a try if you get a chance, thanks !

**Comment by xkcd386at** [comment]
Hi

Apologies for the huge delay!

I tried this just now, as below, and I clearly misunderstood how RUNFILE_ROOTS is supposed to work.  I'll read up a little more and try again.  To answer your question about usage, I have a home-grown function that does this (though its "runfiles" are actually shell source files that are sourced in so the execution is straightforward).  I was hoping to migrate my dozens of such functions to something like this.

Anyway here's my failed attempt to get RUNFILE_ROOTS to work:

    $ run version
    run 0.11.1 (build=v0.11.1 date=2023-01-24T17:09:23Z builder=goreleaser)
    $ pwd
    /home/x3/x/gits/run
    $ cat ~/.runfile
    hello:
        echo hi there
    $ env|grep -i run
    PWD=/home/x3/x/gits/run
    $ RUNFILE_ROOTS=$HOME RUNFILE=.runfile run hello
    run: ERROR: runfile '.runfile' not found: please create the file or specify an alternative

    $ RUNFILE_ROOTS=$HOME run -r .runfile hello
    run: ERROR: runfile '.runfile' not found: please create the file or specify an alternative

    $ cd
    $ RUNFILE=.runfile run hello
    hi there

**Comment by xkcd386at** [comment]
oh it works now; thank you so much!  I've started migrating my little shell functions over :)

**Comment by TekWizely** [comment]
> oh it works now; thank you so much! I've started migrating my little shell functions over :)

Thanks for confirming - Thank you also for sticking with it - I hope you find Run as a worthy replacement for your current setup !
