### ISSUE TITLE
Parsing and processing issue in version 0.11.1

### ISSUE THREAD

**Issue by brunk** [TekWizely/run#72]
I believe I have found an issue with version 0.11.1.  Given the following Runfile, see the output for version `0.10.0` and `0.11.1`

* Version 0.10.0 shows the help text and PHP output of the command.
* Version 0.11.1 does not show the help text or correct run PHP embedded code.

## Runfile
```
# Set default shell for all actions
.SHELL = bash

EXPORT .RUNFILE


## 
# Check configuration
config-check:
    echo "RUNFILE: $RUNFILE"


##
# Run php embedded
# OPTION FLAG_contrived -a <arg> Contrived argument
run-php-embedded (php):
    <?= "PHP_VERSION_ID: " . PHP_VERSION_ID . "\n" ?>
    <?= "FLAG_contrived: {$_SERVER['FLAG_contrived']}\n" ?>
```

## run version 0.10.0
```shell
$ run version
run 0.10.0 (build=v0.10.0 date=2022-11-10T20:57:42Z builder=goreleaser)
$ run list
Commands:
  list                (builtin) List available commands
  help                (builtin) Show help for a command
  version             (builtin) Show run version
  config-check        Check configuration
  run-php-embedded    Run php embedded
$ run config-check
RUNFILE: /Users/brunk/projects/testing/run/Runfile
$ run run-php-embedded -a asdf
PHP_VERSION_ID: 80201
FLAG_contrived: asdf
```

## run version 0.11.1
```shell
$ /opt/homebrew/bin/run version
run v0.11.1
$ /opt/homebrew/bin/run list
Commands:
  list                (builtin) List available commands
  help                (builtin) Show help for a command
  version             (builtin) Show run version
  config-check        Check configuration
  run-php-embedded
$ /opt/homebrew/bin/run run-php-embedded -a asdf
run: ERROR: Runfile:16: command not found: php
```

**Comment by TekWizely** [comment]
Hey @brunk  !!

OK so I should have noticed right away, but it took me debugging the runfile comments to figure it out:

For the header comment:
```
##
# Run php embedded
```

The text `Run` is being interpreted as a command action -- Remember v0.11 introduced the idea of being able to `run` other commands  ... 

Run is trying to invoke another runfile command named `php` but there isn't one, so its erroring out :)

Try changing your comment to `Runs php embedded` and you should have success.

Not sure if we should treat this this as an actual bug or not ...

Either way, apologies for the inconvenience and thanks for reporting it.

-TW

**Comment by brunk** [comment]
I should have seen that! 🤦   I incorrectly assumed that `RUN`, `ASSERT`, `OPTION`, etc. required being written in uppercase.

I have testing in other areas and not using 'run' as the first word fixes the problem.
