### ISSUE TITLE
Suggestions to make using Run more clear

### ISSUE THREAD

**Issue by Gys** [TekWizely/run#80]
Hi

I had not used this tool for a while and was trying to remember how to use it. I also tried to google it, but 'run' and 'Runfile' are very common words...

So I suggest you add a link to your project in the help screen. Plus an option to create a example Runfile with some comments for possible use cases.

**Comment by Gys** [comment]
Ok, have the latest version now and that includes the project. Good one! Still, I think an example Runfile would be nice to get started more quickly in new projects.

**Comment by TekWizely** [comment]
Greetings @Gys !

Thank you for taking the time to create an issue, and double-thanks for taking time to upgrade to latest version to see if your concerns were addressed.

re: Samples

I'd be reluctant to ship a sample Runfile in the binary as it feels a bit wasteful.

The [Examples](https://github.com/TekWizely/run?tab=readme-ov-file#examples) section on the README is pretty thorough.

You could imagine an `examples/` folder in the repo, but not sure it would be valuable if it was based on the same samples as the README.

If it contained some useful real-word examples or templates, that could be very interesting, and possibly related to #8 .

Perhaps it may be enough to update messaging beside the link within help to also state that there are examples to be found, maybe something like:

```
Learn more about run (including example Runfiles) at https://github.com/TekWizely/run"
```

Lemme know what you think and thanks again for taking the time!

Q: I'd be interested in knowing how you're using Run in your own projects?
